Repository fylein/fyle-qbo-api, pull requests merged in 2024-11, with the labels that each got.

#687 feat: Sync account detail type
  .github/workflows/codecov.yml
  apps/quickbooks_online/utils.py
Labels: deploy, size/XS

#689 fix: remove sentry transaction sampling
  fyle_qbo_api/sentry.py
Labels: size/XS

#690 fix: add unique constraint in task_logs for expense_group, add interval for next run
  apps/tasks/migrations/0012_alter_tasklog_expense_group.py
  apps/tasks/models.py
  apps/workspaces/tasks.py
Labels: size/S

#691 chore: bump sdk version
  requirements.txt
Labels: size/XS

#693 chore: Revert "fix: add unique constraint in task_logs for expense_group, add interval for next run (#690)"
  apps/tasks/migrations/0012_alter_tasklog_expense_group.py
  apps/tasks/models.py
  apps/workspaces/tasks.py
Labels: size/S

#695 fix: add default values
  apps/fyle/models.py
Labels: size/XS

#696 fix: Tax Details JE
  apps/quickbooks_online/utils.py
Labels: size/XS

#698 test: Internal APIs
  tests/test_internal/__init__.py
  tests/test_internal/test_actions.py
  tests/test_internal/test_views.py
  tests/test_workspaces/test_views.py
Labels: size/M

#697 feat: Add support for internal APIs
  apps/internal/__init__.py
  apps/internal/actions.py
  apps/internal/apps.py
  apps/internal/migrations/__init__.py
  apps/internal/urls.py
  apps/internal/views.py
  apps/quickbooks_online/utils.py
  apps/workspaces/permissions.py
  apps/workspaces/views.py
  fyle_qbo_api/settings.py
  fyle_qbo_api/urls.py
  requirements.txt
  tests/test_internal/__init__.py
  tests/test_internal/test_actions.py
  tests/test_internal/test_views.py
  tests/test_workspaces/test_views.py
Labels: size/M
