Repository fylein/fyle-qbo-api, pull requests merged in 2024-10, with the labels that each got.

#677 fix: activity mappings stats
  requirements.txt
Labels: size/XS

#678 feat: Add attribute limits
  apps/quickbooks_online/utils.py
  requirements.txt
  tests/test_fyle_integrations_imports/test_modules/test_base.py
  tests/test_fyle_integrations_imports/test_modules/test_categories.py
  tests/test_fyle_integrations_imports/test_modules/test_cost_center.py
  tests/test_fyle_integrations_imports/test_modules/test_expense_custom_fields.py
  tests/test_fyle_integrations_imports/test_modules/test_merchants.py
  tests/test_fyle_integrations_imports/test_modules/test_tax_groups.py
  tests/test_quickbooks_online/test_utils.py
Labels: size/L

#680 feat: Add middleware to log all post requests
  fyle_qbo_api/logging_middleware.py
  fyle_qbo_api/settings.py
Labels: size/S

#681 feat: Adding loggers for workspaces api
  apps/workspaces/views.py
Labels: size/XS

#682 feat: Added loggers in sdk and changed version
  fyle_qbo_api/settings.py
  requirements.txt
Labels: size/XS

#683 feat: Remove warning logger
  fyle_qbo_api/logging_middleware.py
Labels: size/XS

#684 fix: support marking an integration back as active
  apps/workspaces/actions.py
Labels: size/XS

#685 feat: Add few more loggers in permission area
  apps/workspaces/permissions.py
  requirements.txt
Labels: size/XS
