Repository fylein/fyle-qbo-api, pull requests merged in 2025-08, with the labels that each got.

#884 chore: fix new setup migration
  .flake8
  apps/workspaces/templates/mail_template.html
Labels: size/XS

#888 chore: Add drstrange deploy
  .github/workflows/private_deploy.yml
  .github/workflows/qa_deployment.yml
  .github/workflows/staging_deployment.yml
Labels: size/M

#898 fix: change QBO logo
  apps/workspaces/templates/mail_template.html
Labels: size/XS

#899 fix: Sync Tax code, vendor, employee
  apps/quickbooks_online/utils.py
Labels: size/S
