Repository fylein/fyle-qbo-api, pull requests merged in 2025-03, with the labels that each got.

#740 feat: patch `/integrations` on export errors and token expiry
  apps/fyle/helpers.py
  apps/mappings/exceptions.py
  apps/quickbooks_online/actions.py
  apps/quickbooks_online/exceptions.py
  apps/quickbooks_online/tasks.py
  apps/workspaces/actions.py
  fyle_qbo_api/utils.py
  tests/test_exceptions.py
  tests/test_mappings/test_exceptions.py
  tests/test_mappings/test_tasks.py
  tests/test_quickbooks_online/test_tasks.py
  tests/test_quickbooks_online/test_views.py
  tests/test_workspaces/test_actions.py
  tests/test_workspaces/test_views.py
Labels: size/M

#754 fix: Retry stuck tasks export
  apps/internal/tasks.py
Labels: size/XS

#756 fix: Django Vul
  requirements.txt
Labels: size/XS

#758 fix: None tax
  apps/quickbooks_online/utils.py
Labels: size/XS

#760 fix: TLS vulnerability
  .flake8
  Dockerfile
  docker-compose-pipeline.yml
  init.sql
  tests/conftest.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sh
Labels: size/S

#759 fix: use `filter` instead of `get` while invalidating credentials
  fyle_qbo_api/utils.py
Labels: size/S

#761 fix: Add 1 general post accounting call after last export
  apps/quickbooks_online/actions.py
Labels: size/XS

#766 chore: dummy commit to trigger deployment
  README.md
Labels: size/XS

#764 fix: Run container with non root user
  Dockerfile
  docker-compose-pipeline.yml
Labels: size/XS

#769 fix: help article domain
  apps/workspaces/templates/mail_template.html
Labels: size/XS

#768 fix: auto map flag reset
  apps/workspaces/apis/import_settings/serializers.py
  apps/workspaces/apis/import_settings/triggers.py
Labels: size/S

#767 Feat: Add updated_at in updates and bulk update
  apps/fyle/actions.py
  apps/mappings/tasks.py
  apps/quickbooks_online/tasks.py
  apps/workspaces/apis/import_settings/triggers.py
Labels: size/XS

#771 fix: exception handling in import of expenses
  apps/fyle/tasks.py
Labels: size/XS
