Repository fylein/fyle-qbo-api, pull requests merged in 2025-07, with the labels that each got.

#849 fix: last export detail update for real-time users
  apps/workspaces/actions.py
Labels: size/XS

#850 Feat: Fix skip export bug
  apps/fyle/tasks.py
Labels: size/XS

#851 fix: handle UnauthorizedClientError
  apps/quickbooks_online/exceptions.py
Labels: size/XS

#852 Feat: Fix throttling vulnerability
  fyle_qbo_api/settings.py
Labels: size/XS

#854 fix: add worker loggers, skip schedule run if task_log is enqueued
  apps/quickbooks_online/queue.py
  apps/quickbooks_online/tasks.py
  apps/workspaces/actions.py
  apps/workspaces/tasks.py
Labels: size/S

#857 fix: enable/disable multi currency support
  apps/workspaces/helpers.py
  apps/workspaces/signals.py
  tests/test_workspaces/test_helpers.py
Labels: size/M

#860 feat: remove support for item category sync
  apps/quickbooks_online/utils.py
  tests/test_quickbooks_online/fixtures.py
  tests/test_quickbooks_online/test_utils.py
Labels: deploy, size/S

#862 Feat: Bump up version for removing minor version completely
  requirements.txt
Labels: size/XS

#866 fix: account sync
  .github/workflows/pytest.yml
  apps/quickbooks_online/utils.py
Labels: size/XS

#878 fix: Tax amount none
  apps/fyle/models.py
  tests/test_fyle/test_models.py
Labels: deploy, size/XS

#879 chore: Update platform version 2.3.4
  apps/fyle/models.py
  requirements.txt
  tests/test_fyle/fixtures.py
Labels: size/XL

#882 fix: items sync
  apps/quickbooks_online/utils.py
  apps/workspaces/signals.py
  tests/test_quickbooks_online/test_utils.py
  tests/test_workspaces/conftest.py
  tests/test_workspaces/test_signals.py
Labels: deploy, size/M
