Repository fylein/fyle-qbo-api, pull requests merged in 2025-02, with the labels that each got.

#714 feat: Re export Stuck Exports
  apps/internal/actions.py
  apps/internal/tasks.py
Labels: size/M

#734 chore: reexport schedule creation
  apps/internal/migrations/0003_auto_generated_sql.py
  apps/internal/tasks.py
Labels: size/M

#735 fix: retry stuck migration
  apps/internal/migrations/0003_auto_generated_sql.py
Labels: size/XS

#732 fix: Move in progress from chain to function
  apps/quickbooks_online/queue.py
  apps/quickbooks_online/tasks.py
  tests/test_fyle/test_queue.py
  tests/test_quickbooks_online/test_models.py
  tests/test_quickbooks_online/test_tasks.py
Labels: deploy, size/M

#739 test: patch `/integrations` on qbo token expiry
  tests/test_quickbooks_online/test_tasks.py
  tests/test_quickbooks_online/test_views.py
  tests/test_workspaces/test_views.py
Labels: size/S

#738 feat: patch `/integrations` on token expiry
  apps/quickbooks_online/actions.py
  apps/quickbooks_online/exceptions.py
  apps/workspaces/actions.py
  tests/test_quickbooks_online/test_tasks.py
  tests/test_quickbooks_online/test_views.py
  tests/test_workspaces/test_views.py
Labels: size/S

#737 test: test patch integrations settings api
  apps/quickbooks_online/actions.py
  apps/quickbooks_online/exceptions.py
  apps/workspaces/actions.py
  tests/test_quickbooks_online/test_tasks.py
  tests/test_quickbooks_online/test_views.py
  tests/test_workspaces/test_actions.py
  tests/test_workspaces/test_views.py
Labels: size/M

#736 feat: patch `/integrations` on export errors
  apps/fyle/helpers.py
  apps/quickbooks_online/actions.py
  apps/quickbooks_online/exceptions.py
  apps/workspaces/actions.py
  tests/test_quickbooks_online/test_tasks.py
  tests/test_quickbooks_online/test_views.py
  tests/test_workspaces/test_actions.py
  tests/test_workspaces/test_views.py
Labels: size/M

#746 chore: Retry Stuck Task Final
  apps/internal/migrations/0003_auto_generated_sql.py
  apps/internal/tasks.py
Labels: size/M

#747 fix: bill refund
  apps/fyle/models.py
Labels: deploy, size/XS

#743 test: token expiry logic
  apps/exceptions.py
  apps/mappings/exceptions.py
  apps/quickbooks_online/tasks.py
  tests/test_exceptions.py
  tests/test_mappings/test_exceptions.py
  tests/test_mappings/test_tasks.py
  tests/test_quickbooks_online/test_tasks.py
  tests/test_quickbooks_online/test_views.py
Labels: size/M

#742 fix: update flag in qbo_credentials and integrations on token expiry
  apps/fyle/helpers.py
  apps/mappings/exceptions.py
  apps/quickbooks_online/actions.py
  apps/quickbooks_online/exceptions.py
  apps/quickbooks_online/tasks.py
  apps/workspaces/actions.py
  fyle_qbo_api/utils.py
  tests/test_exceptions.py
  tests/test_mappings/test_exceptions.py
  tests/test_mappings/test_tasks.py
  tests/test_quickbooks_online/test_tasks.py
  tests/test_quickbooks_online/test_views.py
  tests/test_workspaces/test_actions.py
Labels: size/M

#712 feat: Add support for skip expense post import of expenses
  apps/fyle/actions.py
  apps/fyle/apps.py
  apps/fyle/helpers.py
  apps/fyle/signals.py
  apps/fyle/tasks.py
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_tasks.py
Labels: deploy, size/L

#750 fix: skip export v2 edge case
  apps/fyle/tasks.py
Labels: deploy, size/XS

#741 fix: pii
  fyle_qbo_api/sentry.py
Labels: deploy, size/M

#751 fix: vulnerabilities
  requirements.txt
Labels: size/XS

#752 fix: Medium vulnerabilities
  requirements.txt
Labels: size/XS
